version: '3.8'

networks:
  kafka-streams-basic-example-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: kafka-streams-basic-example-zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-streams-basic-example-network
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-streams-basic-example-kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    expose:
      - 9093
    networks:
      - kafka-streams-basic-example-network
    depends_on:
      - zookeeper