management:
  server:
    port: 8090
    ssl.enabled: false

logging:
  level:
    example: debug
    root: info

spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    streams:
      application-id: kafka-streams-basic-example-app